# Generated by Django 2.0.6 on 2018-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=32)),
            ],
        ),
    ]
