# Generated by Django 2.0.6 on 2018-06-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
